ls img1 | cut -d '-' -f 1 | uniq | wc -l > type_count.txt
ls img2 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img3 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img4 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img5 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img6 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img7 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img8 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img9 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img10 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img11 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img12 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img13 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img14 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img15 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img16 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img17 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img18 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img19 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
ls img20 | cut -d '-' -f 1 | uniq | wc -l >> type_count.txt
